spring:
  profiles: docker
  application:
    name: discovery-service
server:
  ports:
      - "8061:8061"





eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
   
  server:
    enable-self-preservation: false
  
