spring:
  profiles: docker
  application:
    name: discovery-service
server:
  port: 8061




eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
